<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\XiangqiOnline.Shared\XiangqiOnline.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\Classic\**\*.*" />
    <Resource Include="Assets\Festival\**\*.*" />
    <Resource Include="Assets\Emoji\**\*.*" />
    <Resource Include="Assets\Sea\**\*.*" />
  </ItemGroup>
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>UDM18.Client</AssemblyName>
    <RootNamespace>UDM18.Client</RootNamespace>
  </PropertyGroup>
</Project>
